[package]
name = "ray_tracing_rust"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
egui = "0.17"
egui_wgpu_backend = "0.17"
egui-winit = { version = "0.17", default-features = false, features = ["links"] }
env_logger = "0.9"
log = "0.4"
pixels = "0.9"
winit = "0.26"
winit_input_helper = "0.12"
palette = "0.5"
cgmath = "0.18"
rand = "0.8"
